name: Adhoc_Deploy_Abnahme
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version
      helmTemplate:
        required: true
        description: Version Helm Template
        default: 10.1.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: abnahme
    steps:
      - uses: actions/checkout@v2
      - name: Helm installer
        uses: Azure/setup-helm@v1.1
        with:
          version: "latest"
      - name: Prepare Helm Template
        run: |
          helm registry login ${{ secrets.CONTAINER_REGISTRY }} -u ${{ secrets.CONTAINER_REGISTRY_USER }} -p ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          helm chart pull ${{ secrets.CONTAINER_REGISTRY }}/bp/charts/spring-boot-2:${{ github.event.inputs.helmTemplate }}
          helm chart export ${{ secrets.CONTAINER_REGISTRY }}/bp/charts/spring-boot-2:${{ github.event.inputs.helmTemplate }} --destination ./
        env:
          HELM_EXPERIMENTAL_OCI: 1
      - name: Prepare Manifests
        uses: azure/k8s-bake@v1
        with:
          silent: false
          renderEngine: 'helm'
          helmChart: './spring-boot-2/'
          overrideFiles: './helm/values-abnahme.yaml'
          overrides: |
            version:${{ github.event.inputs.version }}
        id: bake
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_API }}
          k8s-secret: ${{ secrets.KUBERNETES_DEPLOY_SECRET }}
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v1.4
        with:
          namespace: abnahme-beispiel
          manifests: ${{ steps.bake.outputs.manifestsBundle }}

  integration-tests:
    needs: [ "deploy" ]
    runs-on: [ self-hosted, linux, x64 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Cache Maven packages
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run:
          mvn -ntp -B clean test-compile failsafe:integration-test failsafe:verify --file pom.xml -s .github/settings.xml -Dkarate.env=abnahme -Dkarate.options="--tags ~@ignore --tags ~@external" -Duser=$TESTUSER_CREDENTIALS_USR -Dpassword=$TESTUSER_CREDENTIALS_PSW
        env:
          GITHUB_ACTOR: ${{ secrets.PACKAGES_USER }}
          GITHUB_TOKEN: ${{ secrets.PACKAGES_PAT }}
