name: Adhoc_Deploy_Produktion
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version
      helmTemplate:
        required: true
        description: Version Helm Template
        default: 10.1.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: produktion
    steps:
      - uses: actions/checkout@v2
      - name: Helm installer
        uses: Azure/setup-helm@v1.1
        with:
          version: "latest"
      - name: Prepare Helm Template
        run: |
          helm registry login ${{ secrets.CONTAINER_REGISTRY }} -u ${{ secrets.CONTAINER_REGISTRY_USER }} -p ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          helm chart pull ${{ secrets.CONTAINER_REGISTRY }}/bp/charts/spring-boot-2:${{ github.event.inputs.helmTemplate }}
          helm chart export ${{ secrets.CONTAINER_REGISTRY }}/bp/charts/spring-boot-2:${{ github.event.inputs.helmTemplate }} --destination ./
        env:
          HELM_EXPERIMENTAL_OCI: 1
      - name: Prepare Manifests
        uses: azure/k8s-bake@v1
        with:
          silent: false
          renderEngine: 'helm'
          helmChart: './spring-boot-2/'
          overrideFiles: './helm/values-produktion.yaml'
          overrides: |
            version:${{ github.event.inputs.version }}
        id: bake
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_API }}
          k8s-secret: ${{ secrets.KUBERNETES_DEPLOY_SECRET }}
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v1.4
        with:
          namespace: produktion-beispiel
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
